---
- name: set up variables
  set_fact:
    caddy_version: 1.0.4

- name: prepare service group
  group:
    name: svc
    state: present

- name: prepare service user
  user:
    name: caddy
    groups: svc
    shell: /sbin/nologin
    create_home: no
    append: yes
    comment: "Service User"
    state: present

- name: prepare binary directory
  file:
    path: /opt/caddy/{{ caddy_version }}
    state: directory

- name: link binary dir
  file:
    src: "{{ caddy_version }}"
    dest: /opt/caddy/current
    state: link

- name: prepare tmp download dir
  file:
    path: "{{ role_path }}/files/tmp"
    state: directory
  delegate_to: localhost

- name: download caddy binary
  vars:
    dest_path: "{{ role_path }}/files/tmp/caddy-{{ caddy_version }}.tgz"
  get_url:
    url: https://github.com/caddyserver/caddy/releases/download/v{{ caddy_version }}/caddy_v{{ caddy_version }}_linux_amd64.tar.gz
    dest: "{{ dest_path }}"
  delegate_to: localhost
  when: dest_path is not exists
  run_once: True

- name: install caddy
  unarchive:
    src: "{{ role_path }}/files/tmp/caddy-{{ caddy_version }}.tgz"
    dest: /opt/caddy/current

- name: transfer files
  copy:
    src: files/{{ file_path }}
    dest: /{{ file_path }}
    owner: root
    group: root
    mode: preserve
  loop:
    - lib/systemd/system/
    - opt/app/
  loop_control:
    loop_var: file_path

- name: mask caddy service
  systemd:
    name: caddy
    enabled: no
    masked: yes
    state: stopped