---
- name: set vars
  set_fact:
    containerd_version: 1.2.6-3
    docker_version: 19.03.5~3

- name: prepare download dir
  file:
    path: "{{ role_path }}/files/tmp/{{ ansible_distribution_release }}"
    state: directory
  delegate_to: localhost

- name: Download reusable containerd binaries locally
  get_url:
    url: "https://download.docker.com/linux/ubuntu/dists/{{ ansible_distribution_release }}/pool/stable/amd64/containerd.io_{{ containerd_version }}_amd64.deb"
    dest: "{{ role_path }}/files/tmp/{{ ansible_distribution_release }}/containerd-{{ containerd_version }}.deb"
  delegate_to: localhost

- name: Download reusable Docker CE CLI binaries locally
  get_url:
    url: "https://download.docker.com/linux/ubuntu/dists/{{ ansible_distribution_release }}/pool/stable/amd64/docker-ce-cli_{{ docker_version }}-0~ubuntu-{{ ansible_distribution_release }}_amd64.deb"
    dest: "{{ role_path }}/files/tmp/{{ ansible_distribution_release }}/docker-ce-cli-{{ docker_version }}.deb"
  delegate_to: localhost

- name: Download reusable Docker CE binaries locally
  get_url:
    url: "https://download.docker.com/linux/ubuntu/dists/{{ ansible_distribution_release }}/pool/stable/amd64/docker-ce_{{ docker_version }}-0~ubuntu-{{ ansible_distribution_release }}_amd64.deb"
    dest: "{{ role_path }}/files/tmp/{{ ansible_distribution_release }}/docker-ce-{{ docker_version }}.deb"
  delegate_to: localhost

- name: Copy Docker binaries
  copy:
    src: "{{ role_path }}/files/tmp/{{ ansible_distribution_release }}/{{ item }}"
    dest: "/tmp/{{ item }}"
  with_items:
    - "containerd-{{ containerd_version }}.deb"
    - "docker-ce-cli-{{ docker_version }}.deb"
    - "docker-ce-{{ docker_version }}.deb"

- name: Install Docker
  apt:
    deb: "/tmp/{{ item }}.deb"
    policy_rc_d: 101
    state: present
  with_items:
    - "containerd-{{ containerd_version }}"
    - "docker-ce-cli-{{ docker_version }}"
    - "docker-ce-{{ docker_version }}"

- name: mask docker service
  systemd:
    name: docker
    enabled: no
    masked: yes
    state: stopped