---
- name: jq vars
  set_fact:
    jq_version: "1.6"

- name: prepare dir
  file:
    path: "{{ role_path }}/files/tmp"
    state: directory
  delegate_to: localhost

- name: download jq
  get_url:
    url: https://github.com/stedolan/jq/releases/download/jq-{{ jq_version }}/jq-linux64
    dest: "{{ role_path }}/files/tmp/jq-{{ jq_version }}"
  delegate_to: localhost

- name: install jq
  copy:
    src: "{{ role_path }}/files/tmp/jq-{{ jq_version }}"
    dest: /usr/local/bin/jq
    mode: 0755
