---
- name: install ppa tools
  apt:
    name: ['software-properties-common']
    update_cache: no

- name: install ppa
  apt_repository:
    repo: ppa:vbernat/haproxy-2.0

- name: install HAProxy
  apt:
    name: haproxy=2.0.*
    policy_rc_d: 101
    state: present
    update_cache: yes

- name: add to svc group
  user:
    name: haproxy
    groups: svc
    append: yes

- name: copy conf files
  copy:
    src: "{{ role_path }}/files/{{ item }}"
    dest: /{{ item }}
    owner: root
    group: root
    mode: preserve
  with_items:
    - etc/logrotate.d/
    - etc/rsyslog.d/
    - lib/systemd/system/
    - opt/app/

- name: update dir owner
  file:
    path: /var/lib/haproxy
    state: directory
    owner: haproxy

- name: disable haproxy auto start
  systemd:
    name: haproxy
    state: stopped
    enabled: no
    masked: yes
